### ISSUE TITLE
Feature Request: AutoHotkey

### ISSUE THREAD

**Issue by daephx** [maptz/maptz.vscode.extensions.customfolding#1]
## General
Ran a check to make sure the extension worked for starters and had no issues with C#.

![c region test](https://user-images.githubusercontent.com/36192863/45054939-575fe580-b043-11e8-92f5-02734198a634.PNG)
: Just a hello world sample test :

---
## AutoHotkey
AutoHotkey has an issue with /**/ Comments if it is not "actually" separated by a line.

![issue](https://user-images.githubusercontent.com/36192863/45063782-b8e47c00-b064-11e8-80e5-a93f3e529bce.PNG)

![ahk region test](https://user-images.githubusercontent.com/36192863/45055090-ba517c80-b043-11e8-9ba9-7976e0381fbd.PNG)

Personally, I was aiming for an extension that worked similar to this example I found on youtube

![ahk organize referance](https://user-images.githubusercontent.com/36192863/45055129-d5bc8780-b043-11e8-9b3c-49e40a89f2e2.PNG)
I believe he is using sublime text

---
EDIT: I managed to find a way of emulating this by adding indentation to my code but custom regions based off comments would still be a nice addition, so take the information as you will or ignore it,

**Comment by maptz** [comment]
I've updated the extension to support 'ahk' files, on the assumption you use the AutoHotKey language extension. It's currently implemented to fold around `; #region ` tags. 

I'm thinking about updating the extension to allow for per-language customizable of tags. That way you could generate a regex for` ;=================#==========` style regions. I'm not sure when I'll get around to doing that, but for now at least you have folding in ahk files.
