### ISSUE TITLE
Possible to fold things in the same line?

### ISSUE THREAD

**Issue by derricck** [maptz/maptz.vscode.extensions.customfolding#102]
Suppose this is a single line: `#xxx aaaaaaaaaaaaaaaaaaaaaaaaaa. #yyy`

became

`#xxx ...`

I created a detailed description of this request here:
https://stackoverflow.com/questions/72244103/possible-to-collapse-custom-regions

**Comment by maptz** [comment]
The Maptz region folder extension relies on the built in folding provider. As far as I know, it's not able to provide the kind of functionality you're after.  Sorry
