### ISSUE TITLE
Activating extension 'maptz.regionfolder' failed: Cannot find module 'tslib

### ISSUE THREAD

**Issue by cavo789** [maptz/maptz.vscode.extensions.customfolding#103]
Hello

I'm working under Windows (WSL2 enabled) and the extension isn't working on my machine.

If I go to the Developper console of vscode I got this error :

```text
Activating extension 'maptz.regionfolder' failed: Cannot find module 'tslib'
Require stack:
- /xxxxxx/.vscode-server/extensions/maptz.regionfolder-1.0.16/out/engine/Engine.js
- /xxxxxx/.vscode-server/extensions/maptz.regionfolder-1.0.16/out/extension.js
- /xxxxxx/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/loader.js
- /xxxxxx/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/bootstrap-amd.js
- /xxxxxx/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/bootstrap-fork.js.
```

So it's seems that `maptz.regionfolder` rely on `tslib` which seems to be missing on my computer.

Any idea how I can solve this problem?

Thanks.

```text
Name: #region folding for VS Code
Id: maptz.regionfolder
Description: Provides folding for text wrapped with #region comments in VS Code.
Version: 1.0.16
Publisher: maptz
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder
```

````text
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by maptz** [comment]
I believe that this issue is resolved in version 1.0.17. Try updating the extension, and let me know if you still receive this error

**Comment by cavo789** [comment]
So fast... Thanks

The version `1.0.17` is not available through vscode

![2022-06-03_08h25_32](https://user-images.githubusercontent.com/355999/171798918-985ac56f-253b-4d58-be46-c7531a34a605.png)

Will check how to install `1.0.17`...

By going on https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder I can see there `1.0.17` but clicking on the install button start vscode back and install `1.0.16`.  (I've previously removed the extension).

Something on my side?

**Comment by cavo789** [comment]
My version of vscode is `1.63.2` while `1.66.x` is available; I'll ask my ICT department to force the update (since I can't due to company rules). Will let you know if I can then install the latest version.  Thanks!

**Comment by cavo789** [comment]
Good morning

Sorry for the delay, finally I was able to upgrade to vscode `1.67`.  I can confirm the problem has disappeared after installing version `1.0.17`.

The region code folding is now working back; that's really great.

Thanks!
