### ISSUE TITLE
Toggle the fold state, of the current region the cursor is in?

### ISSUE THREAD

**Issue by JustinLebo** [maptz/maptz.vscode.extensions.customfolding#105]
The idea is the cursor can be anywhere within the region (either the region declaration line, or within the region content), and there would be a command that would toggle the fold state of that region only.

So say the region starts in a folded state. You put your cursor anywhere on the region declaration line (as that's the only line that's visible) and press some hotkey to run "regionFolder.toggleCurrentRegion". 

The region will then unfold, and you can see everything inside. After you're done editing the region, or if it's not what you expect press the SAME hotkey to toggle the region fold state and move on to other parts of the file.

**Comment by maptz** [comment]
Hi @JustinLebo ,

What's the big advantage of this over the built-in region folding mechanism where `ctrl+shift+[` expands the current region and `ctrl+shift+]` ? The only advantage is having one key rather than two. Is that all you're after?

Or am I missing something? Is there further behaviour here that you think would be advantageous?

**Comment by JustinLebo** [comment]
> The only advantage is having one key rather than two. Is that all you're after?

Yes that's what I'm hoping to accomplish. Also the default command bound to `ctrl+shift+[` is `editor.fold`.

`editor.fold` does not guarantee the region will fold. If you have a foldable block inside your region, that block will fold instead. Ie in the screenshots below the block comment folds instead of the region tag:

![image](https://user-images.githubusercontent.com/108893245/181775042-9d4e5fc2-1835-4dcd-be4e-d80e4fc63517.png)

![image](https://user-images.githubusercontent.com/108893245/181775095-f1a3b4e3-3998-40bb-a757-398c8fd8eba0.png)

**Comment by maptz** [comment]
Hi @JustinLebo , 

This is definitely something for the VS Code folding mechanism and not for this extension. I'm going to mark this as closed.
