### ISSUE TITLE
Possible python formatting problem with adding folding version 1.0.18

### ISSUE THREAD

**Issue by MagicBOTAlex** [maptz/maptz.vscode.extensions.customfolding#108]
It worked exactly like it was advertised for the first 4 or 5 regions but then it stopped adding folding to the newly created regions. 

Before formatting loads:
![image](https://user-images.githubusercontent.com/44818698/203437031-04beb304-f422-4501-82ee-d854817a4cce.png)

After formatting loaded:
![image](https://user-images.githubusercontent.com/44818698/203437051-5c9cfa5a-1d2d-4982-9c1c-3ccfd6a1304c.png)

Note: I am new to Python but almost fluent in C#. I'm also new to VS code.

**Comment by MagicBOTAlex** [comment]
Update: Apparently some of that text just messes something up
![image](https://user-images.githubusercontent.com/44818698/203440060-d2c77c06-4d88-4ffd-a45a-e2c8855c47d6.png)
Because everything else works

![image](https://user-images.githubusercontent.com/44818698/203440111-e706716a-b3d6-479d-9ea9-a828d032d74e.png)


Apparently any of those 4 lines of code is not wrap-able:
![image](https://user-images.githubusercontent.com/44818698/203440256-509fe185-24da-4eb7-8078-69f2bc247d24.png)
![image](https://user-images.githubusercontent.com/44818698/203440282-665adc09-1549-40b1-b0a2-fa3d457a9a86.png)
![image](https://user-images.githubusercontent.com/44818698/203440307-83723ac2-ca54-4005-811c-cfb092b89a13.png)
![image](https://user-images.githubusercontent.com/44818698/203440326-e8200fd2-e0e9-4137-8282-0a60f7e5f551.png)
![image](https://user-images.githubusercontent.com/44818698/203440349-fdea311c-56a2-471c-a200-88b134671412.png)


Even wrapping that code with print doesn't work:
![image](https://user-images.githubusercontent.com/44818698/203440498-f5320260-7a1e-41ad-b370-cce91e2e6f8a.png)


Anyway, sorry for bothering you but I guess that the easiest fix for this is just not to fold that chunk of code.

**Comment by MagicBOTAlex** [comment]
I found the fix...
![image](https://user-images.githubusercontent.com/44818698/203440808-83a6f831-0607-4d35-9c8b-de18b6c52937.png)
Apparently, you are not able to fold the last code in a function.

**Comment by maptz** [comment]
Hmm. Can you send the text that you're unable to fold?

It's possible that the question mark is what's causing the region to fail "yes?"

**Comment by MagicBOTAlex** [comment]
I've had python problems before, so it could be just my problem.

I created a new script called "test.py" with contents: 
```
def thisIsTesting():

    # region 
    print()
    # endregion
```

and this is the result:
![image](https://user-images.githubusercontent.com/44818698/203869636-14ca048d-96ba-4431-bf51-c16aeeed4f3b.png)
No folding.

**Comment by maptz** [comment]
Yeah. Python is a mess I'm afraid. It's either region folding, or the default indent-based folding. It's not possible to do both, or wasn't when I last looked at this a few months ago.

**Comment by MagicBOTAlex** [comment]
I tried again with but with text for the #region:
![image](https://user-images.githubusercontent.com/44818698/203869777-e47a825d-58d6-4d3d-b5c1-05e5f1bf4448.png)

I don't know what is wrong but i'm not forcing you to fix this at all. (i don't like python)

**Comment by maptz** [comment]
I have occasionally tried to solve this python issue. I like you am not particularly keen on it as a language and so have not been particularly motivated to push the rock uphill.

**Comment by MagicBOTAlex** [comment]
Haha. I'm forced to learn it because of school but yeah. Thank you for your responses.

**Comment by kcvinker** [comment]
> I found the fix... ![image](https://user-images.githubusercontent.com/44818698/203440808-83a6f831-0607-4d35-9c8b-de18b6c52937.png) Apparently, you are not able to fold the last code in a function.

Hi, thank you for this tip. I was going to uninstall this extension, because, the past part of my class was not folding. I tried some other regexes and no way. Your comment saved me.
