### ISSUE TITLE
Can I set it to fold SVG tags by default?

### ISSUE THREAD

**Issue by Keavon** [maptz/maptz.vscode.extensions.customfolding#111]
I'm looking to make my HTML files, with inline SVG tags, fold the verbose SVG syntax by default when I open the HTML file. I don't want to actually write out the region comments, though. I tried this configuration but it doesn't seem to be working:

```json
"maptz.regionfolder": {
	"[html][markdown]": {
		"defaultFoldStartRegex": "\\<svg.*?\\>",
		"foldEnd": "</svg>"
	},
	"collapseDefaultRegionsOnOpen": true
}
```

Is what I'm trying to do possible? What's the right way to configure it?

**Comment by trogper** [comment]
try making it two separate configs: `"[html]": { ...` and `"[markdown]": { ...` instead of `"[html][markdown]": { ...`

**Comment by trogper** [comment]
@maptz please provide us a resolution. Is the thing I wrote the correct solution? Does your config support one config for multiple multiple languages, or does every language have to be specified separately?

**Comment by Keavon** [comment]
I unfortunately won't be able to try it myself soon since I've already removed the code (and my entire use case for this).

**Comment by maptz** [comment]
Hi @trogper , Your solution is correct. Every language has to be specified separately. The folding provider is generated based on matching the document type provided int he settings. 

I understand your desire to merge multiple selectors, but I think it adds unnecessary complexity to the code just to avoid copying two separate configs.

**Comment by Keavon** [comment]
Ok, thanks! Just for some context, it never would have even occurred to me that this was failing due to my conjoining the two since that's provided out of the box in VS Code's settings JSON parsing. Am I right in concluding that you are parsing the languages yourself? I realize this might add complexity, but I'll counterbalance that by suggesting it causes UX confusion due to the divergent behavior from that provided by VS Code itself using the same pattern. Anyways, your call but hopefully that helps explain my perspective. Thanks!

**Comment by maptz** [comment]
Hmm. Good point. I'll look into that.
