### ISSUE TITLE
Feature request: support region/endregion as well as #region/#endregion

### ISSUE THREAD

**Issue by unikitty37** [maptz/maptz.vscode.extensions.customfolding#114]
I'm working on a codebase which already has region comments that have been added by users of JetBrains IDEs, which use `region` and `endregion` rather than `#region` and `#endregion`. I've tested `#region`/`#endregion` in a JetBrains IDE and it doesn't recognise them, so changing all the region comments wouldn't go down too well 😁 

Would it be possible to have a setting to switch the hash matching on and off? That way, VS Code users can turn it off on a per-project basis when working with JetBrains users.

**Comment by maptz** [comment]
I'm not sure I totally understand, but have you tried just adding a `disableFolding` setting for the language in the .vscode settings for the project? 

```
"maptz.regionfolder": {
    "[csharp]": {                                  
        "disableFolding": true
  }
}
```

**Comment by unikitty37** [comment]
Thanks — what I meant is probably best shown with this JavaScript code:

```js
// #region One
const one = 'one'
// #endregion

// region Two
const two = 'two'
// endregion
```

I can fold the first region in VS Code using the extension, but not the second. A JetBrains IDE will fold the second region, but not the first, because it doesn't support the hash character before `region`.

(As someone switching from RubyMine to VS Code, I'd also like to not have to change the comments in my existing projects!)

Ideally, the hash would be optional and I'd be able to use either format in VS Code. A per-project setting as to whether or not to enable the hash might avoid cases where someone expects `// #region One … // endregion` to work, though…

**Comment by maptz** [comment]
What about just making the `#` optional in the regex for javascript, and not inserting the # during a region insert?

```
 "[javascript]": {
    foldEnd: "/* endregion */",
    foldEndRegex: "/\\*[\\s]*[#]*endregion",
    foldStart: "/* region  [NAME] */",
    foldStartRegex: "^[\\s]*/\\*[\\s]*[#]*region[\\s]*(.*)[\\s]*\\*/[\\s]*$"
  },
```

**Comment by unikitty37** [comment]
Thanks — that could work, but I was just using JavaScript as the illustration — I'd need to do it for JavaScript, TypeScript, Ruby, HTML, and probably several others in the project I'm thinking of, and then repeat it on multiple projects.

Rather than using per-project settings, I'd end up duplicating DefaultConfiguration.ts in my global settings, which would let me do it once — but then I'd be incompatible with projects that use the hash character unless I edit the per-project config for those projects.

I was hoping there would be an easy way to add a simple boolean flag. I suspect that wouldn't be so easy, though — it looks like you'd need something `foldStartRegex` and `foldStartRegexWithoutHash`.

Given I'd like to have the region insert use line comments rather than block comments, I suspect I'm going to need to do a fair bit of customising anyway, so I'll duplicate the config into my VS Code settings. Does the default config change particularly often?

**Comment by maptz** [comment]
Well, couldn't you just have a setting file in each project where it's an issue? Wouldn't that be by far the simplest solution?

I don't think it would be particularly difficult to do add some of the logic to the extension, but I don't think it would serve the extension itself well to try to accommodate it within the main branch as I don't see a general use for it and I've found that increasing the complexity is only valuable when the result is obvious.

I'd definitely recommend forking the repo and trying it out. There's nothing complicated in the code.

The DefaultConfiguration changes quite rarely these days. Occasionally someone submits an obscure language as a pull request, but if you're not using the latest flavour of MYMADEUPLANG, you'll probably not be missing much anyway.

**Comment by unikitty37** [comment]
Yes, I think that probably is going to be easiest. I'll do that — thanks!

I'm having trouble getting it to work for TypeScript, though. This is what I have in `settings.json` — just the hash characters removed:

```ts
    "maptz.regionfolder": {
        "[typescript]": {
            "foldEnd": "// endregion",
            "foldEndRegex": "/\\*[\\s]*endregion",
            "foldStart": "// region [NAME]",
            "foldStartRegex": "^[\\s]*/\\*[\\s]*region[\\s]*(.*)[\\s]*\\*/[\\s]*$"
        },
        "[typescriptreact]": {
            "foldEnd": "// endregion",
            "foldEndRegex": "/\\*[\\s]*endregion",
            "foldStart": "// region [NAME]",
            "foldStartRegex": "^[\\s]*/\\*[\\s]*region[\\s]*(.*)[\\s]*\\*/[\\s]*$"
        },
    }
```

…and yet it still folds on `#region`/`#endregion` and not `region`/`endregion`, even after completely quitting and restarting VS Code. (I'm not using React, but I added that section just in case).

What have I done wrong here?

**Comment by maptz** [comment]
Hi, 

I think there is an issue with the extension on the current version of VS Code. I'm investigating.

**Comment by maptz** [comment]
Ok. I've found the issue.  It's to do with the way the new default folding is working in VS Code and your attempt to fold based on a simple comment. 

Take the following pattern, which matches on `// aregion Some region` -> `// aendregion`
```
{
    "maptz.regionfolder": {
        "showRegionsInOutline": true,
        "[typescript]": {
            "foldEnd": "// aendregion",
            "foldEndRegex": "^[\\s]*//[\\s]*aendregion",
            "foldStart": "// aregion [NAME]",
            "foldStartRegex": "^[\\s]*//[\\s]*aregion[\\s]*(.*)[\\s]*"
          },
       
    }
}
```

This would work correctly with the following code:

```
//import * as signalR from "@microsoft/signalr";

var s = "";
  
// aregion Some region 
export namespace funcs {
    export function init() {
        console.log("Initializing engine");
        const engine = new Engine();
        engine.initialize().then(p => {
            console.log("Engine initialized");
        });
    }
}
// aendregion

```

But if you lose the line `var s="";`, then it won't work. 

This is because VS Code now implements a default folding strategy on top of which the Maptz folding provider works. If any ranges from the maptz folding provider overlaps with one of the default ranges, then it causes an issue. 

The official docs say:

> Multiple providers can be registered for a language. In that case providers are asked in parallel and the results are merged. If multiple folding ranges start at the same position, only the range of the first registered provider is used. If a folding range overlaps with an other range that has a smaller position, it is also ignored.

The reason the case above doesn't work without the `var` line, is because: a block of comments is treated as a single collapsible block by the default folding provider. The new commented line intersects with the default range specifying the comment, and so the custom fold is ignored 

As a result, I don't think you'll get good results trying to get your use case to work with `// region` text. 

I believe you are better off using a `/* region` pattern to define your folds. For instance, the following folds withuot an issue:

```
//import * as signalR from "@microsoft/signalr";


/* region MyRegion */
export namespace funcs {
    export function init() {
        console.log("Initializing engine");
        const engine = new Engine();
        engine.initialize().then(p => {
            console.log("Engine initialized");
        });
    }
}
/* endregion */
```

The settings for this look like:

```
{
    "maptz.regionfolder": {
        "showRegionsInOutline": true,
        "[typescript]": {
            "foldEnd": "/* #endregion */",
            "foldEndRegex": "/\\*[\\s]*#*endregion",
            "foldStart": "/* #region [NAME] */",
            "foldStartRegex": "^[\\s]*/\\*[\\s]*#*region[\\s]*(.*)[\\s]*\\*/[\\s]*$"
          },
       
    }
}
```

**Comment by unikitty37** [comment]
Thanks — I'll do it that way, in that case.

I see there's `editor.defaultFoldingRangeProvider` — it's possible that setting that to `MohammadBaqer.better-folding` might solve that problem, but it's entirely possible that it will break more than it fixes :)
