### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Franz333** [maptz/maptz.vscode.extensions.customfolding#116]
Hi,
I know it will sound weird but does the extension work for .txt files? 
Thanks

**Comment by AlexanderTheGr8-gr** [comment]
Have you tried in configurations: [plaintext] ?
When I hit "change language mode" (Ctrl-k m)
Js is displayed as: ```Babel Javascript (javascript)```
While Plain Text as: ```Plain Text (plaintext)```
So maybe this part shows the defined / V.Code internal language name you need to define in cofniguration.

For example:
```
"maptz.regionfolder": {
    "[plaintext]": {                                      //Language selector
        "foldEnd": "; #endregion",                    //Text inserted at the end of the fold
        "foldEndRegex": ";[\\s]*#endregion",          //Regex used to find fold end text.
        "foldStart": "; #region [NAME]",              //Text inserted at the start of the fold.
                                                    //Use the `[NAME]` placeholder to indicate
                                                    //where the cursor should be placed after
                                                    //insertion
        "foldStartRegex": ";[\\s]*#region[\\s]*(.*)",  ////Regex used to find fold start text.
        "disableFolding": false //Turn off #region folding for this language
  }
}
```
(See: https://github.com/maptz/maptz.vscode.extensions.customfolding#configuration)

**Comment by Franz333** [comment]
No I had not tried this yet
But actually my situation is a bit specific because I am using robot framework and I need to ask vscode to treat .txt files with this framework in the "files.associations" settings section
Anyway, it turns out that the setting the "disableFolding" property to "fase" was the answer..

For those bumping into the same problem:

    "files.associations": {
        "*.txt": "robotframework",
    },
    "maptz.regionfolder": {
        "[python]": { //Language selector
            "foldEnd": "#endregion", //Text inserted at the end of the fold
            "foldEndRegex": "[\\s]*#endregion", //Regex used to find fold end text.
            "foldStart": "#region [NAME]", //Text inserted at the start of the fold.
            //Use the `[NAME]` placeholder to indicate
            //where the cursor should be placed after
            //insertion
            "foldStartRegex": "[\\s]*#region[\\s]*(.*)", ////Regex used to find fold start text.
            "disableFolding": false //Turn off #region folding for this language
        },
        "[robotframework]": { //Language selector
            "foldEnd": "#endregion", //Text inserted at the end of the fold
            "foldEndRegex": "[\\s]*#endregion", //Regex used to find fold end text.
            "foldStart": "#region [NAME]", //Text inserted at the start of the fold.
            //Use the `[NAME]` placeholder to indicate
            //where the cursor should be placed after
            //insertion
            "foldStartRegex": "[\\s]*#region[\\s]*(.*)", ////Regex used to find fold start text.
            "disableFolding": false //Turn off #region folding for this language
        }
    },
