### ISSUE TITLE
Bug with copy all

### ISSUE THREAD

**Issue by hoainam1593** [maptz/maptz.vscode.extensions.customfolding#12]
After I fold my code, then Ctr+A, Ctr+C. It just copy /**#region Functions */ instead of actual inside code.
PS: My code: /**#region Copy */

var a = function() {

}

/**#endregion */

**Comment by maptz** [comment]
Hi @hoainam1593 , I've looked into this. It's the default behaviour on VS code with or without my extension installed. You will have to log an issue on the vscode repo.
