### ISSUE TITLE
Feature Request: php Support

### ISSUE THREAD

**Issue by JaPawel** [maptz/maptz.vscode.extensions.customfolding#16]
It would be great to be able to use this extension in `php` files.

**Comment by maptz** [comment]
Thanks. I've incorporated this in the new version.

**Comment by JaPawel** [comment]
@maptz Thanks for the new version. Is it possible to override base configuration? Now `IConfiguration.ts` overrides `settings.json` (I think..). Better (in my opinion) would be, if `settings.json` config overrides `IConfiguration.ts` config.

Not sure why, but after update I have lost default `php` folding (for comments, functions, classes, etc). I have disabled all extensions to be sure. For now unfortunately have to disable this extension.

**Comment by maptz** [comment]
Yes. You can override the base configuration just by adding an object to your usual vscode settings files. For e.g. in a `.vscode` folder, in a `settings.json` file:

```
{
"maptz.regionfolder": {
    "[php]": {                                      //Language selector
        foldEnd: "; #endregion",                    //Text inserted at the end of the fold
        foldEndRegex: ";[\\s]*#endregion",          //Regex used to find fold end text.
        foldStart: "; #region [NAME]",              //Text inserted at the start of the fold.
                                                    //Use the `[NAME]` placeholder to indicate
                                                    //where the cursor should be placed after
                                                    //insertion
        foldStartRegex: ";[\\s]*#region[\\s]*(.*)"  ////Regex used to find fold start text.
  }
}
```

With regard to the default `php` folding, as I'm not a php person, can you give me an example some text that used to fold and now doesn't with the extension provided? 

We're experiencing the same issue with the C/C++ files too. The C/C++ extension doesn't actually provide any custom folding functionality and relies on the default vs code folding. I suspect the php extension does the same. The default vs code folding just works on text indentation, but is disabled as soon as any extension provides folding information (which this extension does). 

It would be great if you could show me an example so I can see if the same thing is happening here, as I'm going to talk to the vscode team to see if they can recommend a solution here.

**Comment by JaPawel** [comment]
Thanks, now in v1.0.3 overriding works.

Without extension:
<img width="421" alt="without" src="https://user-images.githubusercontent.com/8151020/54659170-0ab89500-4ad1-11e9-9c35-07341514595f.png">

With extension:
<img width="429" alt="with" src="https://user-images.githubusercontent.com/8151020/54659169-0ab89500-4ad1-11e9-9ec9-4d61d47024dd.png">

Code:
```
<?php

class Test
{
    /* #region Asd */
    /**
     * @var int
     */
    private $property;

    public function __construct(int $property)
    {
        $this->property = $property;
    }

    public function getProperty(): int
    {
        return $this->property;
    }
    /* #endregion */
}
```

**Comment by ghost** [comment]
It doesn't seem to work with top level php elements. The following has no folding support. I copied the configuration you gave above into my settings.json (with syntax fixes to missing property quotes)

```
/* #region Storefront adjustments/overrides */
// Override functions that emit headers onto pages/posts
function storefront_homepage_header() {}
function storefront_page_header() {}
function storefront_post_header() {}

// Override function that emits edit post link onto posts
function storefront_edit_post_link() {}
/* #endregion */
```
