### ISSUE TITLE
I can't get the extension to work

### ISSUE THREAD

**Issue by felixakiragreen** [maptz/maptz.vscode.extensions.customfolding#17]
Code Version 1.32.3 (1.32.3)
a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4

regionfolder 1.0.3

The commands don't show up in my command palette. I tried manually writing regions and that didn't work either. Is there something basic I'm missing?

**Comment by maptz** [comment]
Hi @xenophilicibex ,

There was an issue in which the command wasn't showing up in the command palette. I've updated the extension in version 1.0.4 to fix this issue. Now if you select some text, and then open the command palette and type `wrapWithRegion`, you should be able to insert wrappable text. 

Alternatively, you can select some text and use the key binding `ctrl+m ctrl+r`. 

Please note, you will need to be in a supported document type (e.g. csharp) with the language service installed.
