### ISSUE TITLE
How does this differ from the preexisting support for #region?

### ISSUE THREAD

**Issue by BlueRaja** [maptz/maptz.vscode.extensions.customfolding#19]
According to [this page](https://code.visualstudio.com/docs/editor/codebasics#_folding), VS Code has supported `#region` since its release.  What does this plugin add to that?

**Comment by maptz** [comment]
Hi @BlueRaja, This extension creates folding wraps based on `#region` comments as opposed to `#region` directives. How the comments are instantiated depends on the language (and is customizable), but in c#, for instance, you can create regions with the following pseudocode:

```
/* #region Some region */
public class SomeClass {
}
/* #endregion */
```

I'd be interested to know if you found this ambiguous in the description and, if so, where you read the description?
