### ISSUE TITLE
Using custom region problem with foldStartRegex

### ISSUE THREAD

**Issue by FatehAK** [maptz/maptz.vscode.extensions.customfolding#20]
I'm trying to make your extension work with my own defined custom regions. I have configured it as follows -
``` "maptz.regionfolder": {
    "[javascript]": {
      "foldStart": "//*",
      "foldStartRegex": "//\\*\\w*",
      "foldEnd": "//*end",
      "foldEndRegex": "//\\*\\w*"
    }
  }
```
I have tried using this config but dosen't seem to work. On further research I found out that the problem is with the foldStartRegex. It seems to expect further characters other than '*'. So the following works:

`"maptz.regionfolder": {
    "[javascript]": {
      "foldStart": "//*-",
      "foldStartRegex": "//\\*\\-\\w*",
      "foldEnd": "//*end",
      "foldEndRegex": "//\\*\\w*"
    }
  }`
On adding a '-' to the start regex it seems to work. Can you help me fix this problem since I would very much like use '*' alone.

**Comment by maptz** [comment]
Hi @FatehAK,

The issue you were having is that the `foldStartRegex` captures the end tags as well as the start tags. We should probably detect for this circumstance and throw an error. 

You need a negative lookahead. I think you want something like:

```
{
  "maptz.regionfolder": {
    "[javascript]": {
      "foldEnd": "//*end",
      "foldEndRegex": "^\/\/(\\*)end[\\s]*$",
      "foldStart": "//*",
      "foldStartRegex": "^\/\/(\\*)((?!end)[\\s\\w]*)$"
    }
  }
}
```
