### ISSUE TITLE
Feature Request: Default collapsed

### ISSUE THREAD

**Issue by hackwaly** [maptz/maptz.vscode.extensions.customfolding#21]
Add an option to make all region default collapsed when open new file.

Additionally: We can add a syntax to comment directive to specify the default collapsed option to the region which comment attached.

Proposal:
```
#region(collapsed) ABC
#endregion
```

**Comment by maptz** [comment]
Hi,

Good ideas. This should all be pretty doable. I'll look into it shortly.

**Comment by aktxyz** [comment]
would love to see this as well !

**Comment by aktxyz** [comment]
some format like the following would be great, this way it's up to the user to decide which regions fold by default (ie any region name that matches /collapse\//

```
// #region collapse/somename
...
// #endregion
```

**Comment by maptz** [comment]
I've implemented this (kind of). Have a look at the Markdown configuration in the latest version which contains a new option: 'defaultFoldStartRegex'

defaultFoldStartRegex: "\\<!--[\\s]*#region\\(collapsed\\)[\\s]*(.*)",

I can't quite get it to work when you open up a new text document, so for the moment you have to press Ctrl+Shift+M Ctrl+Shift+R to collapse default folds.

**Comment by hunger** [comment]
Did you make any progress on this feature yet?

I have huge copyright statements in all files and I want to have them default-folded on document load. I do want to see code, not legal statements about using that code.

**Comment by maptz** [comment]
Hi @hunger ,

I'm currently not able to find a way of running a command when both the page has opened and any language service has done its first pass on the document which is what I'd need to do this.  I don't believe this event is actually support by VS Code unfortunately at the moment.  I can't find anyone at the VS code team who can help me with it though.

The best I can suggest at the is suggest that you issue the `regionfolder.collapseDefault` once the page is opened?

**Comment by patroza** [comment]
@maptz thanks for the great plugin.
it looks look this plugin does it https://marketplace.visualstudio.com/items?itemName=bobmagicii.autofoldyeah

but perhaps that works differently due to not having a dependency on first pass of language server or so?

**Comment by maptz** [comment]
Good find. This doesn't seem to use the language service registration, but it does just set an interval to check things. There's no reason we couldn't do exactly the same thing to check if a language service has been registered for the language and then collapse default regions then. 

I'll try to do this at the weekend.

**Comment by maptz** [comment]
I've included support for this feature in the latest version of the extension (v1.0.11-preview1).

Since I am unable to publish preview versions of the extension and quite a lot of code has changed. I'm keeping this in the preview stack before publishing it to the Marketplace..

If you get a chance, please test this latest version.
