### ISSUE TITLE
Default folding  for Lua doesn't work within this extension

### ISSUE THREAD

**Issue by FalleverX** [maptz/maptz.vscode.extensions.customfolding#26]
This extension is pretty good for fold code chunk! But it will forbid vscode default folding for functions in Lua file.
Consider this situation,sometimes I need to fold a single function without use `-- #region`  in comment ,because it just temporary need,I will unfold the function later. This is inconvenient for me.

_vscode default folding doesn't work_
![image](https://user-images.githubusercontent.com/15180187/63206340-2e662280-c0e5-11e9-8495-92c96b00803c.png)

**Comment by KamNull** [comment]
Got this extension today for Lua, and have the same issue. Hope it can be resolved soon.

**Comment by maptz** [comment]
We have the same issue with the C/C++ language service, and it seems to be because of the language service there. I'm looking into it.

**Comment by maptz** [comment]
I'm migrating this issue to a known issue as it appears for multiple other languages. The issue is #40
