### ISSUE TITLE
Support for Arduino *.ino files

### ISSUE THREAD

**Issue by sheariley** [maptz/maptz.vscode.extensions.customfolding#27]
I use VSCode for Arduino development and I'd love to have this work for the *.ino file type.

**Comment by maptz** [comment]
I'll have a look at this. What are the region formats you'd suggest?

**Comment by sheariley** [comment]
I'd suggesting using the typical c++ comment formats and being able to collapse methods and other "containers" that use the curly braces.
Something like this:
``` c++
// #region Global Variables
... code goes here ...
// #endregion Global Variables

void myMethod() {
... code goes here ...
}
```

Thanks a million!

**Comment by maptz** [comment]
Support should be there for .ino files as it is recognized as a cpp file I believe. 

Please note, there is a known issue for cpp files. Using this extension breaks the custom folding provided by the C/C++ language service. See issue #40 for further details.
