### ISSUE TITLE
Extension disables all code folding

### ISSUE THREAD

**Issue by aaron-jencks** [maptz/maptz.vscode.extensions.customfolding#29]
I installed this extension, because being able to use `#region` folding is super nice, but it's disabled all other code folding in VSCode so now I can't even collapse a function

I'm using Ubuntu, VSCode 1.38.1
Extension version: 1.0.5

**Comment by maptz** [comment]
Are you using this with the C/C++ extension, or what language?

**Comment by aaron-jencks** [comment]
C/C++

**Comment by maptz** [comment]
This appears to be an issue with the C/C++ language service and the way that implements its folding. I've been trying to get the language service authors to look into it, but no joy so far. I'll keep this issue open until I'm able to do this.

**Comment by aaron-jencks** [comment]
Sweet, thanks fam

**Comment by mvaraujo** [comment]
> Are you using this with the C/C++ extension, or what language?

I'm having the same issue with PHP.

VS Code 1.39.2
Extension 1.0.5

**Comment by Clocktown** [comment]
> C/C++

For C/C++, simply use `#pragma region <regionname>` and `#pragma endregion`. Code folding is supported for this (without enclosing it in comments), including Fold All Regions and Unfold All Regions functionality.

**Comment by aaron-jencks** [comment]
I'm not sure if this still needs to be open now, since using `pragma` statements can achieve the same functionality, obviously this solution won't work for php
