### ISSUE TITLE
Feature Request: Lua Support

### ISSUE THREAD

**Issue by tjcouch1** [maptz/maptz.vscode.extensions.customfolding#3]
I would love to have a way to do Lua comment regions! I tried to add it myself, but I couldn't get the source code to run while I was debugging in VSCode... I don't have any experience with VSCode extensions or TypeScript, and there were errors that I suppose I needed to fix for the extension to work.

Lua comment regions would work as follows:

~~~~
--#region Things

function Hello()
  print("Hello")
end

--#endregion

--#region Stuff

function World()
  print("World")
end

--#endregion
~~~~

I have some things written in `extension.ts` that might be helpful (they weren't hard, but I might as well include them):
~~~~
Line 99:
    "markdown",
    "lua"];
~~~~
~~~~
Line 133:
private static getLuaStyleRegions() {
        var retval = new RegionText();
        retval.start = "--#region ";
        retval.end = "--#endregion";
        retval.nameInsertionIndex = ImNotQuiteSureWhatThisDoesSoIllLetYouSetIt;
        return retval;

    }
~~~~
~~~~
Line 157:
            case "lua":
                return LanguageIdRegionLookup.getLuaStyleRegions();
~~~~

I imagine there's other stuff you would need to do, but I'll let you figure that out since you actually know what you're doing.

Thanks! This is a great extension, and it would be fantastic with Lua support!

**Comment by maptz** [comment]
Yes. This should be straightforward. I'll try this out.

**Comment by maptz** [comment]
I'm implementing this today. It should be available in the next release
