### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by haakonstorm** [maptz/maptz.vscode.extensions.customfolding#30]
VSCode is routinely used to edit configuration for Home Assistant, YAML files, I think the language parser it uses is basically the standard yaml parser + it adds autocompletions via connecting to the HA API. Would it be possible to add custom folding to Home Assistant? Can I create something myself to make this happen? I could try somehow having customfolding treat Home Assistant language as any other yaml file, but I'm not sure how. :)
Config files for HA tend to get large and native Yaml folding isn't the best for this particular issue, so custom folding would be awesome. Especially if its possible to NEST foldings! (?)

**Comment by maptz** [comment]
Yes. This should be possible. 

Are the Home Assistant files just .yaml files? If so the latest version of the extension - which supports yaml files - should allow you to create customised folds.
