### ISSUE TITLE
How do I transform existing python rules?

### ISSUE THREAD

**Issue by 625781186** [maptz/maptz.vscode.extensions.customfolding#37]
![image](https://user-images.githubusercontent.com/30521429/72614509-6bbd2d80-396d-11ea-8ae2-1af7f6f29098.png)

I tried many times but failed, so I gave up.

test code:
```python


# <editor-fold desc="system">
import sys
import builtins

# </editor-fold>

# <editor-fold desc="install">
from loguru import logger

from PyQt5.QtWidgets import QStyleFactory

# </editor-fold>

## <editor-fold desc="myself">
## config: debug env
builtins.IIDEBUG = True
from Tools.myIC import ic

from loguru import logger

builtins.IILogger = logger
builtins.IIC = ic

#############################
from E5Gui.E5Application import e5App, E5Application
from FindFileDialog import FindFileDialog

## </editor-fold>


```

**Comment by maptz** [comment]
Hmm. A very good question. 

I've implemented a default folding format for python now in the settings in the latest version, but it appears non-trivial to override the default folding logic. The actual folding is implemented by the python language service and appears not to interact well with 3rd party folding extensions. 

I have the same issue with C/C++ and others.  I'm looking at how I could resolve this issue.
