### ISSUE TITLE
Bug: Collapsing *.sql with -- comment without prefixed space on line

### ISSUE THREAD

**Issue by sunamo** [maptz/maptz.vscode.extensions.customfolding#4]
Hello, 

I'm very appreciate your extension, it's really cool. I have one wish - please add support to fold region in *.sql file with comment without any space before starting mark --.

If exists this code:

/* #region LOOP */
        Select * from table
-- fold            
        where id = 1
/* #endregion */

region will be collapsed just to line 3, despite of exists /* #endregion */ on the end. 
But is working fine:

/* #region LOOP */
        Select * from table
 -- fold            
        where id = 1
/* #endregion */¨

Or please tell me what is influicing this behaviour and workaround.

In C# everything works fine, for SQL I use https://marketplace.visualstudio.com/items?itemName=mycelo.oracle-plsql and don't know how folding working with language support extension.

Many thanks

**Comment by maptz** [comment]
Yes. This should be quite doable. I'll look into it today.

**Comment by maptz** [comment]
I've added support for .sql files which is, I think, the issue you are seeing. It will work in the next released version of the extension. I will close this when I release the next version.
