### ISSUE TITLE
fix change log data

### ISSUE THREAD

**Issue by rlodbrok** [maptz/maptz.vscode.extensions.customfolding#41]
In vscode the auto extension update  reports availability of 1.0.7 however no details are available regarding this new version.

problem 1) the changelos (in readme) contains v1.0.5 while the package seems to be at 1.0.7.

problem 2) the project changelog seems to be located in the readme instead of a separate changelog.

thank you in advance!

**Comment by maptz** [comment]
Very good points. Should be resolved now.
