### ISSUE TITLE
command 'regionfolder.collapseAllRegions' not found

### ISSUE THREAD

**Issue by WixoLeo** [maptz/maptz.vscode.extensions.customfolding#44]
I installed the plugin,
Added this to my typescript react

```javascript
/* #region(collapsed) */
import * as React from 'react';
import {
  MessageBoxFunctionalLayout,
  Text,
  Table,
} from '../../../../../components/Commons/WSR';
/* #endregion */
```

Added this into my settings.json:

```javascript
"maptz.regionfolder": {
    "[typescriptreact]": {
      "defaultFoldStartRegex": "\\<!--[\\s]*#region\\(collapsed\\)[\\s]*(.*)",
      "foldEnd": "<!-- #endregion -->",
      "foldEndRegex": "\\<!--[\\s]*#endregion",
      "foldStart": "<!-- #region [NAME] -->",
      "foldStartRegex": "\\<!--[\\s]*#region[\\s]*(.*)"
    }
  }
```

Tried running the command and it threw this error:
`command 'regionfolder.collapseAllRegions' not found`

**Comment by maptz** [comment]
Hmm. You are right! There was an odd mismatch between two of my machines.

Should now be correct in version 1.0.10

**Comment by WixoLeo** [comment]
> Hmm. You are right! There was an odd mismatch between two of my machines.
> 
> Should now be correct in version 1.0.10

Thanks!
