### ISSUE TITLE
Feature Request: Allow for more than one pattern per language

### ISSUE THREAD

**Issue by hunger** [maptz/maptz.vscode.extensions.customfolding#46]
Please provide a way to register several patterns for one language.

**Comment by maptz** [comment]
This should be fairly doable. I'll implement it in the next version.

**Comment by maptz** [comment]
Actually, thinking about this, it isn't so obvious how this would work. 

There is currently one *insertion* command `regionfolder.wrapWithRegion` which is supposed to pair with the regex pattern used to recognize it. Having more than one regex pattern implies there would be more than one kind of insertion command available - which means an arbitrary number of insertion commands. This isn't impossible, but could get pretty inelegant pretty quickly. 

The simplest solution at the moment is to create a Regex that matches multiple patterns.

`[\s]*#endregion(s)*` matches both `#endregion` and `#endregions`.

What's the actual use case you are after?

**Comment by hunger** [comment]
My ultimate use case is to auto-fold the copyright headers of C/C++ files.

My naive approach was to match "^/\* ?\*\*\*\*\*\*\*\*\*\*" with an end-region of "\*\*\*\*\*\*\*\*\*\* ?\*/$". I would of course like to have anything defined by customfolding in addition to that.

**Comment by maptz** [comment]
Ok. I understand. I working on automatic folding upon opening now. 

Adding multiple patterns slightly complicates the region algorithm, along with breaking the supposed 1:1 correspondence between the region definition and the region insertion. Neither issue is insurmountable, but I'd like to think about it for a bit before introducing unnecessary complexity.

**Comment by steinhaug** [comment]
My usecase is PHP files, where I also have HTML in same file. So while the <!-- is for HTML I do need the /* for PHP.

I guess this is a general "problem" in vs code since the folding is not working in the HTML of a PHP file anyways.

**Comment by maptz** [comment]
Understood. The same could be said of Razor or any other 'mixed' language.

I'll try to implement a new algorithm for the folding in the next pass including multiple possible match patterns. I'll need to accommodate certain issues that didn't crop up before (conflicting regions of different types).

**Comment by maptz** [comment]
Hi, 

I've now added the ability to define multiple folds per language. 

Secondary folds are defined in a `foldDefinitions` property for each language. By settting the `isFoldedByDefault` value to `true`, you can ensure that the folds are collapsed by default when the file opens. 

The example below is used to collapse Copyright style headers by default in Javascript files:

```
/***************************************************
 * Copyright (c) 2020 Maptz.
 * All rights reserved.
 ***************************************************/
```
The `.vscode/settings.json` file used to define this behaviour is:
```
{
  "maptz.regionfolder": {
    "[javascript]": {
      "foldEnd": "/* #endregion */",
      "foldEndRegex": "/\\*[\\s]*#endregion",
      "foldStart": "/* #region [NAME] */",
      "foldStartRegex": "^[\\s]*/\\*[\\s]*#region[\\s]*(.*)[\\s]*\\*/[\\s]*$",
      "defaultFoldStartRegex": "^[\\s]*/\\*[\\s]*#region[\\s]*default\\s(.*)[\\s]*\\*/[\\s]*$",
      "foldDefinitions": [
        {
          "foldEndRegex": "\\*+/[\\s]*$",
          "foldStartRegex": "^[\\s]*/\\*\\*+" ,
          "isFoldedByDefault": true
        }
      ]
    }
  }
}
```

This is currently in a testing phase in version `1.0.11-preview3`. 

I can't publish  `preview` releases to the VS Code Extension gallery, but I'd be grateful if anyone interested could test and run this preview from the Github source code and let me know how it goes.

**Comment by maptz** [comment]
Now active in the new release
