### ISSUE TITLE
[Solved] Doesn't work at all

### ISSUE THREAD

**Issue by JCKodel** [maptz/maptz.vscode.extensions.customfolding#49]
Installed latest version from VSCode Extension toolbar.

No folding are being made in dart files (although shortcuts to create folding do its job).

**Comment by maptz** [comment]
It's working on my machine with Dart files. Can you send me some way to repro this along with some details of what your setup is?

**Comment by JCKodel** [comment]
Trying to figure out what to provide to you, I found the issue:

```json
"editor.foldingStrategy": "indentation"
```

With this setting, this extension won't work. Just get rid of this setting and it works fine now.

**Comment by maptz** [comment]
Thanks @JCKodel . That's good to know. 

I believe this is what `editor.foldingstrategy` is designed for. When it is on, it turns off other folding strategies (such as the one provided by this extension`. See issue here (https://github.com/Microsoft/vscode/issues/46944)

**Comment by dufferzafar** [comment]
I'm experiencing this issue as well. As in, the region folder doesn't work at all. I have `"editor.foldingStrategy": "indentation",` in my config.

As you can see, the folding marks don't appear:

![image](https://user-images.githubusercontent.com/1449512/82689708-8d5e5680-9c78-11ea-827d-c841b73c1865.png)


When using Remote SSH, should this extension be installed on the remote machine or the local machine? I've tried both though - doesn't work in any case.

Any idea how I can debug this further?

**Comment by maptz** [comment]
Hi @dufferzafar 

The `indentatation` folding strategy forces vscode to ignore any other folding kind other than indentation. If you set this to `auto` it should work.

**Comment by dufferzafar** [comment]
Hmm, so that worked! But in that case I don't seem to be getting any indentation in Python files. Will see what needs to be fixed.

**Comment by maptz** [comment]
Yes. I believe this is the same issue as this one [here](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40).

It's a problem with the way VS code currently implements code folding. Any registration of a service that provides folding information overwrites any fold information provided by the language service. It's maddening! I'm trying to get it sorted.

**Comment by dufferzafar** [comment]
Oh, then I'll just have to remove this extension I guess :/

BTW, today I found out that there is already some built in support for region folding: https://code.visualstudio.com/updates/v1_17#_folding-regions

How is it different from this extension?

**Comment by maptz** [comment]
Yes. That's right. 

This doesn't do the same thing as the built in region folding. It's for custom comment folds above and beyond the language regions. In c# for instance, the built in folding works for #regions (a language directive). This extension allows you to define areas in //#regions. How useful that is depends on your language I suppose.

**Comment by dufferzafar** [comment]
So, I've uninstalled this extension, and left the `foldingStrategy` to remain on `indentation` and in Python and Javascript `#region` folding works correctly.

The only minor issue I have is that it is set to auto-fold so all regions get folded automatically when you open such a file. Just have to get used to it I guess?
