### ISSUE TITLE
Bug: Upon activating no more default C-folding

### ISSUE THREAD

**Issue by Thomseeen** [maptz/maptz.vscode.extensions.customfolding#5]
As soon as I enable the extension in VSCode (Win10) "normal" C-folding for functions, loops, structs, etc. is not longer available / not longer shown. I hope this is a bug and not a feature. Otherwise a setting to prevent that would be awesome.

**Comment by maptz** [comment]
Hi @Thomseeen ,

Apologies for the delay in replying to this. I'm not seeing this on my system, but I'm not an experienced C programmer. Is this just for C projects? Can you upload an example project, and list your extensions?

**Comment by Thomseeen** [comment]
Hey @maptz ,

thanks for replying. A minimal example to reproduce this for me is a single *.c-file with:
```C
/* #region Main */
void main(void) {
    int foo = 1;
    if (foo) {
        foo = 0;
    }
    return foo;
}
/* #endregion */
```
With your extension enabled I'm only able to fold at the `#region` comment. With your extension disabled I'm able to fold the function block `main` and the `if`-clause. I would like to be able to fold at all of these three lines/blocks.
Same example in javascript works just as expected.
```javascript
/* #region Test */
function main() {
    var foo = 1;
    if (foo) {
        foo = 0;
    }
    return foo;
}
/* #endregion */
```
I suspect it has to do with the `C/C++` extension wich is a dependency of `PlatformIO IDE`.
Other active extensions are `One Dark Pro`, `C/C++`, `PlatformIO IDE` and `Python`. I can also include my user settings here:
```json
{
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.pythonPath": "C:\\Python27\\python.exe",
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: chromium, indent_width: 4, column_limit: 200}"
    ],
    "editor.formatOnSave": true,
    "C_Cpp.clang_format_style": "{BasedOnStyle: Chromium, IndentWidth: 4, ColumnLimit: 200}",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "editor.showFoldingControls": "always",
    "git.enableSmartCommit": true,
    "workbench.colorTheme": "One Dark Pro Vivid",
    "git.confirmSync": false,
}
```

**Comment by maptz** [comment]
Yes. I see your problem now. I think this might be an issue with the way the c/c++ language service implements its folding information as I'm not seeing this issue with other language services. I'll do a bit of digging!

**Comment by Thomseeen** [comment]
Hey @maptz ,
any updates on this? I would like to include it in my project/source files.

**Comment by maptz** [comment]
Hi @Thomseeen ,

I'm afraid not. I had a quick look a few weeks back, but wasn't able to find the solution then. I'm hoping to find some time again soon to look into it. 

Stephen

**Comment by maptz** [comment]
I've had another look at this, but can't find any way of solving it through my extension. I've logged a bug on the language extension repo [here](https://github.com/Microsoft/vscode-cpptools/issues/3315)

**Comment by Thomseeen** [comment]
Thank you :) , I will keep track of it there.

**Comment by maptz** [comment]
I've just seen from the issue I raised on the C/C++ extension that that the C/C++ extension doesn't do any custom folding. It relies on the built-in default folding that is in VS Code which is indentation based. When you override FoldingRangeProvider which `Maptz.VSCode.Extensions.CustomFolding` does to provide its functionality, this overrides the built-in indentation folding (see [here](https://github.com/Microsoft/vscode/issues/50991)). There appears to be no way to re-implement the default folding behaviour short of writing indentation based folding again. 

There are two options: 

- Try to implement the default folding behaviour. 

- Wait until the C/C++ extension provides proper folding support. As soon as the C/C++ extension provides folding support (see [here](https://github.com/Microsoft/vscode-cpptools/issues/407)), the appropriate folding behaviour should return for C/C++ files.

**Comment by Thomseeen** [comment]
... so it's not on your end. I will follow the issue and wait till they implement their own folding for C/C++. Thank you for investigating :)
