### ISSUE TITLE
Can't get it to work with ruby

### ISSUE THREAD

**Issue by drewpereli** [maptz/maptz.vscode.extensions.customfolding#50]
Wondering what I'm doing wrong. In my settings.json

```
"[ruby]": {
      "foldStart": "# region [NAME]",
      "foldStartRegex": "#[\\s]*region[\\s]*(.*)[\\s]*",
      "foldEnd": "# endregion",
      "foldEndRegex": "#[\\s]*endregion[\\s]*(.*)[\\s]*",
    }
```

**Comment by maptz** [comment]
Yes. Just looked at this. This isn't working properly with Ruby. I'll have to look into it, but I believe it may be something to do with the ruby language service itself.

**Comment by maptz** [comment]
Interestingly, it looks like the fold regions do actually get registered, and if you make some edits to the document, they appear correctly. This looks like a bug in VS Code to me - or at least in the way that the Language Service interacts with the folding mechanism. 

I'll look into it and add an issue to the VS Code repo if necessary

**Comment by yofreke** [comment]
I may be misconfiguring something, but am having a similar issue with `terraform` language (`.tf` extension). Assuming `[terraform]` is the correct language selector, am I experiencing the same issue?

**Comment by Hobbyte8** [comment]
I'm trying to use this with elm, but it doesn't seem to work. Maybe I did something wrong, but would it be possible that this is a similar issue?

**Comment by maptz** [comment]
> I may be misconfiguring something, but am having a similar issue with `terraform` language (`.tf` extension). Assuming `[terraform]` is the correct language selector, am I experiencing the same issue?

Can you create a new issue with this?

**Comment by maptz** [comment]
Are you still having issues with the Ruby files? I'm not having trouble with simple files on my machine. If you are, can you send me an example ruby document?

**Comment by drewpereli** [comment]
@maptz No more issues, it's working for me. Thank you 🙏
