### ISSUE TITLE
Ability to comment code when adding a region to that code

### ISSUE THREAD

**Issue by wapenshaw** [maptz/maptz.vscode.extensions.customfolding#51]
Hey! Love the extension, use it a lot, but I have one specific usecase that I am currently using a work around for. 

Select the text -> CTRL+M, CTRL+C? comments the selected text and then adds the region comments comments accordingly 

Just mimicking Alt+shift+a but with region functionality.

**Comment by maptz** [comment]
Yes. This is doable. I'll look at it over the weekend.

**Comment by maptz** [comment]
Hi. This has now been implemented in the new version of the extension. The command is `regionfolder.wrapWithRegionAndComment`.

**Comment by wapenshaw** [comment]
Yay! Thanks!
