### ISSUE TITLE
Doesn't work for R

### ISSUE THREAD

**Issue by MrJGao** [maptz/maptz.vscode.extensions.customfolding#54]
As the title, I'm writing R in VS Code, I'd like to use this extension if it can support R. Thanks.

**Comment by maptz** [comment]
Hi,

I'll add a default R implementation in the next official release. In the meantime, you can add R support by adding an `r` section to your settnigs. 

```
"maptz.regionfolder": {
   "[r]": {
       foldEnd: "#endregion",
       foldEndRegex: "[\\s]*#endregion",
       foldStart: "#region [NAME]",
       foldStartRegex: "[\\s]*#region[\\s]*(.*)"
  }
}
```

**Comment by maptz** [comment]
This feature has now been added by default into the next release of the extension. As there are some major changes in the latest version, it's currently a preview release and so isn't available from the Extension Gallery yet. 

I'll release it into the Extension Gallery when verison `1.0.11-preview3` is deemed to be stable.
