### ISSUE TITLE
Doesn't work using Latex and python with adjusted fold text

### ISSUE THREAD

**Issue by VHeusdens** [maptz/maptz.vscode.extensions.customfolding#57]
Hi! I'm trying to make this work for my latex and python code. In the case of python, the standard "#region" works well:
```
"maptz.regionfolder": {
    "[python]": {
      "foldStart": "# #region [NAME]",
      "foldStartRegex": "#[\\s]*#region[\\s]*(.*)",
      "foldEnd": "# #endregion",
      "foldEndRegex": "#[\\s]*#endregion",
      "defaultFoldStartRegex": "#[\\s]*#region\\(collapsed\\)[\\s]*(.*)"
    }
  }
```
However, when I change "#region" to "$region" the right code is inserted on pressing the keyboard shortcut but it doesn't collapse anymore:
```
"maptz.regionfolder": {
    "[python]": {
      "foldStart": "# $region [NAME]",
      "foldStartRegex": "$[\\s]*#region[\\s]*(.*)",
      "foldEnd": "# $endregion",
      "foldEndRegex": "#[\\s]*$endregion",
      "defaultFoldStartRegex": "#[\\s]*$region\\(collapsed\\)[\\s]*(.*)"
    }
  }
```
results in 
```
# $region 
some code...
# $endregion
```
But it won't collapse.

For latex code there is no standard code at all, but adding this to settings.json results in the same behavior as for the customized python settings:
```
"maptz.regionfolder": {
    "[latex]": {
      "foldStart": "% #region [NAME]",
      "foldStartRegex": "%[\\s]*#region[\\s]*(.*)",
      "foldEnd": "% #endregion",
      "foldEndRegex": "%[\\s]*#endregion",
      "defaultFoldStartRegex": "%[\\s]*#region\\(collapsed\\)[\\s]*(.*)"
    }
}
```
Results in 
```
% #region 
some code...
% #endregion
```
But it won't collapse.

Am I doing something wrong?

**Comment by maptz** [comment]
Hi,
Thanks for using the extension .

In the first case, I think your regex isn't right. The `foldStartRegex` and `foldEndRegex` values are used to recognize the regions, while the `foldStart` and `foldEnd` settings are used for the inserts. In Regex `$` is a reserved letter, so I think yuo need:

```
"maptz.regionfolder": {
    "[python]": {
      "foldStart": "# $region [NAME]",
      "foldStartRegex": "$[\\s]*\\$[\\s]*#region[\\s]*(.*)",
      "foldEnd": "# $endregion",
      "foldEndRegex": "#[\\s]*\\$endregion",
      "defaultFoldStartRegex": "#[\\s]*\\$region\\(collapsed\\)[\\s]*(.*)"
    }
  }
```

I'm not sure about the Latex case just yet. VSCode does need to recognize the file as Latex which usually means the appropriate language server has to be installed, and the language selector `latex` needs to be correct. I'll have into this when I'm next in front of my dev machine.

**Comment by VHeusdens** [comment]
Thanks for your suggestion! The following code works, both for python and for latex:

```
"maptz.regionfolder": {
    "[python]": {
      "foldStart": "# $region [NAME]",
      "foldStartRegex": "#[\\s]*\\$region[\\s]*(.*)",
      "foldEnd": "# $endregion",
      "foldEndRegex": "#[\\s]*\\$endregion",
      "defaultFoldStartRegex": "#[\\s]*\\$region\\(collapsed\\)[\\s]*(.*)"
    },
    "[latex]": {
      "foldStart": "% $region [NAME]",
      "foldStartRegex": "%[\\s]*\\$region[\\s]*(.*)",
      "foldEnd": "% $endregion",
      "foldEndRegex": "%[\\s]*\\$endregion",
      "defaultFoldStartRegex": "%[\\s]*\\$region\\(collapsed\\)[\\s]*(.*)"
    }
  }
```

This is going to help me a lot with writing my code :) Thank you for making this extension!

**Comment by maptz** [comment]
Great. 

I don't know `Latex`, but is this an appropriate default fold for the language? i.e. Should we put this into the extension as the `Latex` default?

**Comment by VHeusdens** [comment]
Latex is a language for writing books, reports, etc, I'm using maptz to easily fold long commented pieces of text. The code provided above results in the behavior seen below, so I think it is appropriate as default. Cheers!

![image](https://user-images.githubusercontent.com/36879731/96372794-efa87e00-1168-11eb-91fd-5e50909a77bf.png)
![image](https://user-images.githubusercontent.com/36879731/96372801-f7682280-1168-11eb-95b4-29b1dde03ec2.png)
