### ISSUE TITLE
Extension interfering with python folding 

### ISSUE THREAD

**Issue by VHeusdens** [maptz/maptz.vscode.extensions.customfolding#58]
When I have this extension enabled, my 'regular' python folding doesn't work anymore. I have changed the extension keybindings but I don't suppose this has any relevant effect?

**Comment by skyslide22** [comment]
i got the same problem with PHP, normal folding (class, functions, if else etc) is "removed", the arrow at the left is not there...

i disabled every extension i had, just enabled this one, and the folding died, after the extension was loaded (2-3s after vscode is opened with my/any php file)

**Comment by ragaar** [comment]
I had the same issue with LaTeX. Below is the custom definition I am using.

It properly recognizes the region and allows me to fold. However, after a brief moment (around 1-2s) the extension no longer appears to function and the folding is removed.

```
  "maptz.regionfolder": {
    "[LaTeX]": {
      "foldStart": "% #region [NAME] %",
      "foldStartRegex": "\\%[\\s]*#region[\\s]*(.*)"
      "foldEnd": "% #endregion %",
      "foldEndRegex": "\\%[\\s]*#endregion",
    }
  }
```

The brief moment, mentioned above, seems to be the same duration it takes to update the status bar with the various assessments of the document (e.g., Spaces, Line location, CRLF, etc.)

**Comment by ragaar** [comment]
I discovered my issue was tied to the `LaTeX Workshop` extension.

**Comment by lastobelus** [comment]
I have this issue with Elixir, using ElixirLS extension, if I add a custom folding definition for elixir.

The built in region folding for vscode only detects region markers that start a line, but the elixir autoformatter indents comments to match code indent. So, I tried using this extension, but have the same issue where **only** regions can be folded.

**Comment by maptz** [comment]
Yes. This issue is with the VS code extension model. I've been trying to get them to help out with it for ages, but I haven't had any luck. I'll keep you posted.

**Comment by maptz** [comment]
Here is the issue which deals with this problem more generally: [Issue 40](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40)
