### ISSUE TITLE
Fold a specific JSON property by default

### ISSUE THREAD

**Issue by rdstevens** [maptz/maptz.vscode.extensions.customfolding#59]
Not sure if this is something this extension can do!

I have a JSON document with an object called "abc" - I'd like to be able to have that object folded by default.

I can't put explicit region tags in.

Is there a suitable regex for this extension which might achieve this?

**Comment by maptz** [comment]
Hmmm. I think I'd probably roll a specific extension for this. I think you'll end up covering too many edge-cases by doing this with this extension. 

But you can certainly take a look at the code here to see how it all works as it shouldn't be hard to roll your own solution.
