### ISSUE TITLE
Feature Request: Collapse all regions at once

### ISSUE THREAD

**Issue by myDevRepo2019** [maptz/maptz.vscode.extensions.customfolding#6]
Would it be possible to add a key combination in order to collapse/expand all regions (only regions) at once?

**Comment by maptz** [comment]
I will look into the feasibility of this. I haven't explored the actual folding process yet in the vs code api, so I don't know whether this is possible just yet. I will try looking today

**Comment by maptz** [comment]
So, it appears there is a command for doing this already. It's called `Fold Marker Regions`,  by default mapped to Ctrl+K, Ctrl+8. The unfold command is mapped to Ctrl+K, Ctrl+9. 

This also unfolds so-called markers in the language. So, for instance, in C# a `#region` will be folded as well as a commented region `//#region`. This is obviously not exactly the feature you have asked for, but I don't easily see a way of just folding commented regions. I think the built-in functionality is pretty close, so let me know if it works for you and I'll close this issue.

**Comment by myDevRepo2019** [comment]
That's fantastic :-) It works perfectly well. Thank you so much for the quick help!!!

**Comment by Vampire2008** [comment]
Could you make F1 command for this? Like "Collapse all #regions".
