### ISSUE TITLE
Issue(?) or Feature Request:  Prevent auto-collapse on file open from stealing focus and cursor position.

### ISSUE THREAD

**Issue by jdevl32** [maptz/maptz.vscode.extensions.customfolding#63]
I have noticed that when you open a file containing auto-collapse regions (for example, `/* #region(collapsed) my-region */`), the process to collapse those regions automatically will do so in a manner in which the cursor/focus move(s) with each region it processes, until finally reaching the last one.  If my last cursor position was somewhere near the top of the file (or anywhere for that matter), it will be undesirably moved/replaced with the position of the last auto-collapsed region.  I think most users would prefer that the cursor/focus remain unaffected while processing the regions.  Also, in my case, some of my files are 10s of 1000s of lines long, and I have 100s or so of auto-collapsed regions.  I have to sit and wait a good minute or so before I can resume working with the file.  And even then, I have to try and remember where it was I was last working in the file, rather than have the last current position in view like would have occurred normally.  It would be a great feature to have the focus/cursor position unaffected while the extension processes regions on initial load of a file.

**Comment by maptz** [comment]
Hi @jdevl32. I'll look into this over the next few days. Thanks for spotting it!

**Comment by maptz** [comment]
I'm implementing a global setting to prevent auto-folding on open
