### ISSUE TITLE
Feature Request:  Process auto-collapsed regions immediately when first created.

### ISSUE THREAD

**Issue by jdevl32** [maptz/maptz.vscode.extensions.customfolding#64]
When creating a new region with auto-collapse specified (for example, `/* #region(collapsed) my-region */`), it would be nice if the region auto-collapsed immediately.  Yes, it's not too much trouble to go to the margin and click to collapse manually.  :)  But it would be a nice feature.  Perhaps it could be controlled by a setting, in case users don't want this behavior.  What would be super awesome is if it auto-collapsed on create, but only once the user moves focus outside of the region block itself!  That way if the user happens to be editing code inside the region, they don't have the region collapse on them before they're done modifying.  Again, this would probably require a setting to control this behavior.  Not all users may find this useful.

By the way, I'm really enjoying this extension.  It's been a real life-saver!!!  Keep up the great work!

**Comment by maptz** [comment]
Have you tried out the Default Folding mechanism. See the `Features` section of the ReadMe. 

If you think there is a revision to the way this works, then please let me know
