### ISSUE TITLE
Issue(?) or Feature Request:  Prevent scrolling with cursor opening collapsed regions.

### ISSUE THREAD

**Issue by jdevl32** [maptz/maptz.vscode.extensions.customfolding#65]
When I scroll/navigate with the cursor into/over a collapsed region, it expands/opens the region.  I think this is not preferred behavior, or perhaps a setting could control it.  To reproduce:

1. Collapse a region.
2. Place cursor on line just before collapsed region.
3. Use arrow-down key to (attempt to) move cursor over region.

Once the cursor enters the region block, it expands the once-collapsed region.  I would prefer to have the region remained collapsed.  The cursor should "hop over" (if that makes sense) the collapsed region, effectively "landing" on the next line just after the collapsed region.  In fact, I think this should be the case for any collapsed region, anywhere, any time.  Perhaps the general rule should be that a collapsed region must remain collapsed no matter what, until the user manually expands the region, or some setting determines it should expand.

**Comment by maptz** [comment]
I'd love to see this behaviour too, but it's unfortunately controlled by VS Code natively rather than by the control. You're best off trying to open this as a feature on the main VS Code repository.
