### ISSUE TITLE
Regex to match CSharp default regions.

### ISSUE THREAD

**Issue by melMass** [maptz/maptz.vscode.extensions.customfolding#66]
Hi,

Thanks for this addon I use it all the time.
I'm switching from Rider back to VSCode for Unity, and it's a convention to simply use `#region [name]`.
I tried the following but it does not work:

```json
  "maptz.regionfolder": {
    "[csharp]": {
      "foldEnd": "/* #endregion */",
      "foldEndRegex": "[\\s]*#endregion",
      "foldStart": "/* #region  [NAME] */",
      "foldStartRegex": "^[\\s]*#region[\\s]*$",
      "defaultFoldStartRegex": "^[\\s]*#region[\\s]*$"
    },
  },
```

Does the addon only parse comments or am I doing something wrong in my regex sequences?

Thanks

**Comment by maptz** [comment]
Hi @melMass ,

The #region directive is part of the c# language spec, and I believe they are already handled by the c# language service. You shouldn't need to add a section for c# at all.

**Comment by melMass** [comment]
@maptz Thanks! by default I disable all extensions and enable them per project, I was simply not using the Microsoft C# server...
