### ISSUE TITLE
Support for mutiple nested regions 

### ISSUE THREAD

**Issue by kilasuit** [maptz/maptz.vscode.extensions.customfolding#69]
Code like ARM Templates occasionally need multiple tiers of regions for code organisation like below which I've actually asked for native region support to support this https://github.com/microsoft/vscode-azurearmtools/issues/1122
```
Region 1
- Region 2
- endregion 2
- region 3 
- endregion 3
end region 1
```
However would I be right in thinking that using multiple definitions per language this could potentially already be achievable in this extension by following a pattern like below
```
section 1
- Region 2
- endregion 2
- region 3 
- endregion 3
end section 1
```
& lastly could mulitple region definitions allow for further multiples of regions that say instead replaced the region keyword entirely with say
```
VM 1
- VMExtension 1
- endVMExtension 1
- Policy1 
- endPolicy 1
endVM 1
```

**Comment by maptz** [comment]
I'm not sure I fully understand this, but I'm pretty sure this is already possible. Nested regions are already supported within VS Code as are multiple region formats per language.

Depending on your language, you will need a bit more theatre around your region names. e.g. `// #region Region 1`

**Comment by maptz** [comment]
Hi @kilasuit , 

Did you solve your problem?
