### ISSUE TITLE
Feature Request: Dart Support

### ISSUE THREAD

**Issue by temirfe** [maptz/maptz.vscode.extensions.customfolding#7]
Can you please add Dart support since it's becoming popular due to Flutter?

**Comment by maptz** [comment]
Yes. Happily. Can you help me with the comment structure in Dart? It looks like something along the lines of `// #region REGION NAME` would work best.

**Comment by temirfe** [comment]
It could be even simplier like `//region RegionName ` but `// #region` works too, thanks

**Comment by maptz** [comment]
I don't know Dart well so I don't know if there is a syntactical class, but I like the `#region` syntax in other languages. The prefix marks it immediately as a structural feature rather than just a bit of description.

**Comment by maptz** [comment]
Ok. I've added that to the latest release.
