### ISSUE TITLE
Regions work when manually added to code, but "No region folding available for language". when trying to wrap. Language plugin and server are installed/working, possible to define a rule to use, or copy from language that works?

### ISSUE THREAD

**Issue by MostHated** [maptz/maptz.vscode.extensions.customfolding#76]
Hey there,
    I was trying to use a "regionfolder.wrapWithRegion" hotkey for PowerShell, but it told me that "No region folding available for language 'PowerShell'. Check that you have the language extension installed for these files". I do have the PowerShell plugin and the included language server. Creating a region manually, such as the following works just fine: 

```PowerShell
#region ------
$size = (Get-Host).UI.RawUI.WindowSize
$Host.UI.RawUI.CursorPosition = @{X = 0; Y = ($size.Height - 6) }
#endregion ---
```

Is it possible for me to somehow just let the plugin know to just use the '#' character as the basis for wrapping code in PowerShell? I tried adding the custom rules for a language, but it didn't seem to make a difference.

Though, I am not sure if I have them right? I just copied them from another which seemed like it should be the same.

```jsonc
    // ------------------------------------------------------- Region
    // --------------------------------------------------------------
    "maptz.regionfolder": {
        "[PowerShell, ps1]": {
            "defaultFoldStartRegex": "[\\s]*#region\\(collapsed\\)[\\s]*(.*)",
            "foldEnd": "#endregion",
            "foldEndRegex": "[\\s]*#endregion",
            "foldStart": "#region [NAME]",
            "foldStartRegex": "[\\s]*#region[\\s]*(.*)"
        },
    },
```

Thanks,
-MH

**Comment by maptz** [comment]
Thanks. Should be fixed in release 1.0.15
