### ISSUE TITLE
Does this work without indenting?

### ISSUE THREAD

**Issue by ghost** [maptz/maptz.vscode.extensions.customfolding#77]
I can't seem to get this to work without indenting the content, but at that point I could almost always just rely on the default indent-based collapsing.

I want something like this:
```
#region Region Name
echo What is up homie?
#endregion
```

Is this possible?

**Comment by Man8earPig** [comment]
I wasn't sure why the extension wasn't working until I read this. I wasn't even thinking that it would need to be indented in order to work. Seems like a missed opportunity IMO.

**Comment by ghost** [comment]
Right, without that I'm not sure you gain much from this extension. I guess being able to name regions that are already defined by indent? I guess I'd have to revisit it but really seems weird to have an indentation requirement.

**Comment by maptz** [comment]
It should work without indentation. The indentation depends on the regex pattern defined for the language. Which language are you using?

**Comment by ghost** [comment]
@maptz it's gone through some iteration in my attempts to get it to work, but this is what I have right now:

```json
"[http]": {
    "foldStart": "#region [NAME]",
    "foldEnd": "#endregion",
    "foldStartRegex": "#region[\\s]*(.*)",
    "foldEndRegex": "#endregion(.*)",
    "disableFolding": false
}
```

This seems to have no effect, though the foldStart and foldEnd texts are working given that I can use the "wrap selection with #region tag" command successfully.

Meanwhile, this JavaScript config works fine:
```json
"[javascript]": {
    "foldStart": "/* #region [NAME] */",
    "foldEnd": "/* #endregion */",
    "foldStartRegex": "/\\*[\\s]*#region[\\s]*(.*)",
    "foldEndRegex": "/\\*[\\s]*#endregion[\\s]*\\*/",
    "disableFolding": false
}
```

What am I doing wrong?


Also, is there a reason the example/template uses `[\s]*` and `(.*)` instead of just `\s*` and `.*`? Shouldn't those act the same?

**Comment by maptz** [comment]
Hmmm. I think it's your `http` identifier that's wrong. There needs to be a language server for the files of that type installed.

No reason that I remember for the brackets.  Just for clarity, and the ability to put other identifiers in there.

**Comment by ghost** [comment]
@maptz if I do "choose language mode", HTTP is an option, and it shows at the bottom of the file as the selected language. Maybe that comes from the REST Client extension, but then I would still expect it to be supported. I the same issue with the plaintext "language" – it just doesn't have any effect.  
Is there any type of debug mode I/you could use to see what's going on?

It seems like your extension _does_ recognize HTTP because as I said the "wrap selection with #region tag" command works as expected for HTTP; it's only the folding itself that isn't working.

**Comment by ghost** [comment]
@maptz any feedback here, please? This extension would be an immense help to my daily work if I can get it to work for at least plaintext. Sorry to be a pest, I know my last comment was only 2 days ago.


These are my settings:
```json
"maptz.regionfolder": {
    "[javascript]": {
        "foldStart": "/* #region [NAME] */",
        "foldEnd": "/* #endregion */",
        "foldStartRegex": "/\\*\\s*#region.*",
        "foldEndRegex": "/\\*\\s*#endregion\\s*\\*/",
        "disableFolding": false
    },
    "[http]": {
        "foldStart": "#region [NAME]",
        "foldEnd": "#endregion",
        "foldStartRegex": "#region(.*)",
        "foldEndRegex": "#endregion(.*)",
        "disableFolding": false
    },
    "[plaintext]": {
        "foldStart": "--region [NAME]",
        "foldEnd": "--endregion",
        "foldStartRegex": "--region.*",
        "foldEndRegex": "--endregion.*",
        "disableFolding": false
    }
}
```

JavaScript works as expected, the others do not. I do have both http and plaintext as language options when working with a file. You can see I've experimented with `(.*)` vs `.*` just for jollies.

**Comment by maptz** [comment]
Hi @james-klein-sfcc . I will have a look. Give me 48 hours.

**Comment by maptz** [comment]
I've looked at this. Your `plaintext` regex is wrong.  
Put the following text in your  Workspace settings file (`.vscode/settings.json`).
```
{
    "maptz.regionfolder": {
        "[plaintext]": {
            "foldStart": "--region [NAME]",
            "foldEnd": "--endregion",
            "foldStartRegex": "\\-\\-region.*",
            "foldEndRegex": "\\-\\-endregion.*",
            "disableFolding": false
        },
    }
}
```

I don't know about the HTTP one. I don't know what file format it is, or what language service is providing the HTTP format.

**Comment by ghost** [comment]
~~Ah, it makes sense to have to escape the dashes.~~ Dashes don't need to be escaped, based on regex101.com. However, despite copying-and-pasting your snippet above verbatim, it still doesn't work. I also tested switching the file's language mode to JavaScript and that folding is still working.
https://i.imgur.com/YCrkKP9.png
(There's not a lot I can show with a screenshot, but the icon next to the file name indicates the active language is `plaintext` and although you can't see it, my cursor is hovering in the margin of line 3 where I would expect a dropdown arrow to appear, to collapse the region.)

The HTTP format is what it sounds like and it's provided by the [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) extension.
If plaintext was working for me, I'd ask if there's anything I could ask the author of REST Client via an Issue; but given that plaintext still isn't working, I think it makes sense to focus on that for now. I'm at a loss as to what could be going wrong here.

**Comment by ghost** [comment]
Scratch that, I restarted VSCode and folding is working as expected. Previously settings.json changes were taking effect immediately so I'm not sure why a full restart was needed this time.

Thank you for providing this extremely useful feature and helping me get it working.
