### ISSUE TITLE
Plugin doesn't work when using /*  */ to declare region, only with //

### ISSUE THREAD

**Issue by yanivshaked** [maptz/maptz.vscode.extensions.customfolding#78]
When using the following syntax, region declaration works:
```
  // #region Queue operations
  ...
  // #endregion
```

But when using the following syntax, region is not declared:
```
  /* #region Queue operations */
  ...
  /* #endregion */
```

Any help is highly appreciated!

Thanks

**Comment by TolyanDimov** [comment]
> When using the following syntax, region declaration works:
> 
> ```
>   // #region Queue operations
>   ...
>   // #endregion
> ```
> 
> But when using the following syntax, region is not declared:
> 
> ```
>   /* #region Queue operations */
>   ...
>   /* #endregion */
> ```
Hi I have the same problem when working with JSON documents (.vscode/settings.json).
Does anyone know a solution?

**Comment by maptz** [comment]
You would need to write a custom regex for that scenario. What language are you using?

**Comment by TolyanDimov** [comment]
> What language are you using?

My native Russian language. :dancers:

**Comment by maptz** [comment]
Ha. Stupid question gets a stupid answer. 

The folding depends on the detected language of the file that's open in VS Code. A `regex` parses the file for folding points. This regex is specific to the language of the file, and is overridable. 

By defining the appropriate regex you can implement whatever region folding you want.

**Comment by yanivshaked** [comment]
I'm using **dart** language code. Do you need more information?
