### ISSUE TITLE
Disable all languages by default?

### ISSUE THREAD

**Issue by jcrben** [maptz/maptz.vscode.extensions.customfolding#79]
Given https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40 I would rather disable all by default and opt in on a per language basis. Otherwise I can be left scratching my head when folding doesn't work and possibly forget about why.

Would you be amenable to a pull request implementing this?

**Comment by maptz** [comment]
I'm not sure that's a great idea. You'd have to opt-in by default to any functionality. Users would install the extension and then wonder why there was no behaviour - which would be a step backwards for the languages where the language server doesn't interfere with the folding. 

I could look at explicitly disabling the functionality for each language. 

If I get some time, I'll look back at #40  and see if there's any progress on this. It was very frustrating last time I looked at the extension.

**Comment by jcrben** [comment]
Well you wouldn't have to make it a default setting. But disabling it for broken languages could also help i think

**Comment by maptz** [comment]
I see your point. I'd need to collate a definitive list of which languages servers interfere and which don't, but I think I agree.

**Comment by maptz** [comment]
It looks to me like issue #40 has now been fixed. I presume this is no longer necessary
