### ISSUE TITLE
Feature Request: add language support for Dlang / D

### ISSUE THREAD

**Issue by bsdooby** [maptz/maptz.vscode.extensions.customfolding#81]
As the syntax is pretty much C/C++ (Algol, curly braces) based, this would be nice to have :)

**Comment by maptz** [comment]
This should be fairly simple to do. Do you know what the D lang language selector is? Do you have a setting that works well that can be merged into the codebase?

**Comment by bsdooby** [comment]
Hey,

I did not try to customize a setting for D, thus the feature request.
Is there a good howto for writing these selectors?

D is basically C,C++,C#,Java (Algol-style).

Thx
Peter

**Comment by maptz** [comment]
Yes. Have a look at the configuration section of the readme. If that doesn't help let me know as I'd like to make it easy to do.
