### ISSUE TITLE
[Feature Request] Add CMake support

### ISSUE THREAD

**Issue by melMass** [maptz/maptz.vscode.extensions.customfolding#82]
Hi Maptz,

Thanks again for #region!
I wanted to ask for CMake support, this would be very useful as CMake files can be lengthy and I think supporting it would be quite easy.

Thanks

**Comment by melMass** [comment]
Btw I can make a merge request for it but I don't want to read the whole codebase, it might be useful to add a contribution section to the readme, limiting what needs to be read in order to contribute, something along those lines:

### To Contribute a new lang
- Edit file xxx.ts
- add the name of the lang to the config in xxx.json 
- etc

**Comment by melMass** [comment]
Ok I've read it in diagonal, I first thought things were hardcoded in different parts of the codebase, but it looks like I can just add this to DefaultConfiguration.ts?:


```js
"[cmake]": {
    foldEnd: "# endregion",
    foldEndRegex: "[\\s]*#[\\s]*endregion",
    foldStart: "# region [NAME]",
    foldStartRegex: "^[\\s]*#[\\s]*region[\\s]*(.*)[\\s]*$"
  },
```

I'll open a merge request to follow this

**Comment by maptz** [comment]
Hi, 

Many thanks for this PR. Yes, indeed. That's all you need to do - you just need to know the language selector. 

I'll merge the PR. 

In terms of the *contributing a new lang* idea, I'll have a think about how I can do that cleanly and without confusing the ReadMe. Had you seen that you could configure for CMAKE without touching the codebase?

**Comment by melMass** [comment]
Thanks!
Yes I actually understood that after making the PR, I think it's still cool to have it built-in, but I now remember how configurable it is.
