### ISSUE TITLE
wrapWithRegion

### ISSUE THREAD

**Issue by mcaple** [maptz/maptz.vscode.extensions.customfolding#84]
Given the fact that the preview version will allow multiple foldDefinitions is there any way the extension could allow wrapWithRegion to somehow select which of these regions foldDefinition to use. For instance I may have a comment and deprecated comment wrap such as:

![image](https://user-images.githubusercontent.com/811236/127959430-0a79e293-2f3b-4a41-b9e5-259efbb080c3.png)

The foldSuffix is added so that we would see

#!deprecatedcomment
    #! This is a region
    #! With two lines
#!enddeprecatedcomment

and not

#!deprecatedcomment
    # This is a region
    # With two lines
#!enddeprecatedcomment

and comment would likewise be

#comment
    # This is a region
    # With two lines
#endcomment

From here I can use the extension Better Comments to enhance the look of each fold

Thanks for the extension!!!

**Comment by maptz** [comment]
I'm not sure I totally understand. Do you want to be able to specify which folds to use at any one time?

**Comment by maptz** [comment]
I don't see a good way of doing this neatly and without overcomplicating this extension. If you'd like to try to implement it on a separate branch in a way that makes sense, please do let me know.
