### ISSUE TITLE
Feature request: Put name on end region on create

### ISSUE THREAD

**Issue by arsu-leo** [maptz/maptz.vscode.extensions.customfolding#86]
I have allways the same name on #region and on #endregion like this:
```
#region Some section
//Some code...
//
//End of some code
#endregion Some section
```

Would it be possible to create the end region automatically with the name when I type the region and press enter at the end of the line?

**Comment by maptz** [comment]
Yes. This should be possible. I'll look at this in the next pass.

**Comment by maptz** [comment]
I don't see an easy way of implementing this with VS Code. I'd like to keep this extension simple, so am not going to implement this enhancement. I may return io it in some future iteration.
