### ISSUE TITLE
How can I set this up with Python?

### ISSUE THREAD

**Issue by HappyCuppy** [maptz/maptz.vscode.extensions.customfolding#87]
Hello, how can I set this up with Python?

I tried adding in `settings.json` the option:
```
"[python]": {
	"foldStart": "# #region [Name] #",
	"foldStartRegex": "# #region* #",
	"foldEnd": "# #endregion #",
	"foldEndRegex": "# endregion #",

	"disableFolding": false
}
```
and then inserting in some `.py` file:
`# #region my-region #`
<some text/code>
`# #endregion #
And it didn't work.

AFAIK these start region and end region markers satisfy  the regex patterns for start and finish accordingly, yet it still doesn't work. 

Am I doing something wrong?
Am I just assuming incorrectly that this extension supports folding for Python files (`.py`)?

**Comment by tadams42** [comment]
@HappyCuppy I'd managed to make it work with example below... 

Note that language selector in config is `[ahk]` and not `[python]`. 

If I put `[python]`, then command `Command Palette -> Fold All Regions` doesn't fold anything.

```json
{
  "maptz.regionfolder": {
    "[ahk]": {
      "foldStart": "# region [python imports]",
      "foldStartRegex": "[\\s]*# region \\[python-imports\\]",
      "foldEnd": "# endregion",
      "foldEndRegex": ".*# endregion.*",
      "disableFolding": false
    }
  }
}
```

and:

```python
# region [python imports]
import itertools
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal
from typing import ClassVar, Iterator, List, Optional, Type

from tqdm import tqdm

from .foobar import FooBar

# endregion
```

**Comment by maptz** [comment]
Hi, 

You need to put a valid Regex into the Regex properties:
```
"[python]": {
    foldEnd: "# endregion",
    foldEndRegex: "[\\s]*#[\\s]*endregion",
    foldStart: "# region [NAME]",
    foldStartRegex: "^[\\s]*#[\\s]*region[\\s]*(.*)[\\s]*$"
  }
```
