### ISSUE TITLE
Can't appear to add folding to ColdFusion

### ISSUE THREAD

**Issue by ghost** [maptz/maptz.vscode.extensions.customfolding#88]
I can't add folding to "cfml" (ColdFusion).

Here is my folding config:

```
"[cfml]": { //Language selector
	"foldEnd": "<!--- #endregion --->", //Text inserted at the end of the fold
	"foldEndRegex": "<!---[\\s]*#endregion --->", //Regex used to find fold end text.
	"foldStart": "<!--- #region [NAME]", //Text inserted at the start of the fold.
	//Use the `[NAME]` placeholder to indicate
	//where the cursor should be placed after
	//insertion
	"foldStartRegex": "<!---[\\s]*#region[\\s]*(.*)", ////Regex used to find fold start text.
	"disableFolding": false //Turn off #region folding for this language
}
```

![image](https://user-images.githubusercontent.com/23587065/137535955-a2578a68-6116-4a84-94e7-a38e5a7f1255.png)

---

Note: I was able to add folding to SQL and it works, so I should "know what I am doing", so to speak. I copied SQL's configuration and replaced comment style and it does not work.

**Comment by maptz** [comment]
I've got a feeling that regex isn't right. I think you might need to escape the `-` symbol.

**Comment by maptz** [comment]
Did you solve this? I'm going to close this issue shortly if I don't hear from you.

**Comment by ghost** [comment]
I don’t remember. Just close it.
