### ISSUE TITLE
Please add support for .fish files.

### ISSUE THREAD

**Issue by Memphizzz** [maptz/maptz.vscode.extensions.customfolding#9]
Could you please add support for .fish files?

In fish the default #region and #endregion would work fine.

Thanks in advance!

**Comment by maptz** [comment]
Yes. I'll implement this. Can you point me towards a sample .fish file?

**Comment by Memphizzz** [comment]
Awesome, sure, this is one for example: https://github.com/jorgebucaran/fish-cookbook/blob/master/await_example.fish
There is actually nothing special with fish files. They are only a collection of functions in most cases:

```
#region Tests
function test
	echo test
end

function test2
	echo test2
end
#endregion

function xyz
	echo xyz
end
```

**Comment by maptz** [comment]
That's great. The latest version has .fish files supported. Give it a go, and let me know if you have any issues.

**Comment by Memphizzz** [comment]
It works just fine! Thank you very much and keep up the great work!
