### ISSUE TITLE
Error in VS Code  V1.0.16 when selecting Collapse all #regions

### ISSUE THREAD

**Issue by BlakeCMann** [maptz/maptz.vscode.extensions.customfolding#93]
Hello:

Your folding regions extension is a great tool! 

However, the new version 1.0.16 of #regions folding for VS Code is failing in VS Code.

This just started happening today 03/06/2022.

When I installed the older version from 7/10/2018 it worked fine.

Please take a look at your new version as it may have a serious problem.

Regards,
Blake Mann
bmann@ContinuumSoftware.com
CEO Continuum Software Consulting, Inc.

**Comment by maptz** [comment]
Hmm. I'm genuinely not sure what happened with 1.0.16. 

A new version (1.0.17) should now be live. It's working on my local machine. Can you confirm?
