### ISSUE TITLE
Option to return cursor to original line after folding?

### ISSUE THREAD

**Issue by FruitSausage** [maptz/maptz.vscode.extensions.customfolding#95]
When I use the command `regionfolder.collapseAllRegions`, my mouse cursor is moved to the last folded region in the document.  Is there an option to return it automatically to its original position?

My current workaround is to note the line number before folding and using Go to Line after.

**Comment by maptz** [comment]
Hmm. I'm not seeing this behaviour. Can you give me steps to reproduce, including an example file.

**Comment by maptz** [comment]
Closing this issue because of no response.
