### ISSUE TITLE
Custom folding removes native folding

### ISSUE THREAD

**Issue by strider72** [maptz/maptz.vscode.extensions.customfolding#96]
I'm coding in Classic ASP, using the "Classic ASP Syntax and Snippets" add-on for syntax.  Your plugin doesn't natively handle .asp, so I added the following custom config in `settings.json`:

```
    "maptz.regionfolder": {
        "[asp]": {
            "foldEnd": "'endregion",
            "foldEndRegex": "\\'endregion",
            "foldStart": "'region [NAME]",
            "foldStartRegex": "\\'region[\\s]*(.*)"
        }
    }
```

So the following is a region:

'region Some Region Name  
...code code code  
'endregion

It works well, *except* that without the region stuff turned on, the editor also has folding for structures within the code -- functions and such.  When I turn on the custom folding, *only* the region folding works.

Any idea how I can get the native code structure folding working alongside region folding?  I'm pretty sure this works in other languages....

**Comment by maptz** [comment]
I'm afraid this is part of the issue mentioned in this issue [here](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40)
