### ISSUE TITLE
Enabling region folding breaks native folding with Rust

### ISSUE THREAD

**Issue by Electricz0** [maptz/maptz.vscode.extensions.customfolding#99]
When I have #region folding enabled, all of the folding built into Rust language support stops working (curly braces, brackets, parenthesis, etc.).

**Comment by maptz** [comment]
I'm afraid this is part of the problem with default folding in VS Code that's referenced in this issue [here](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40).
